### PR TITLE
Made default properties refactoring and moved some stuff from chise level to sbgnviz level

### PR DESCRIPTION
**Pull request by metincansiper**
Please see https://github.com/iVis-at-Bilkent/sbgnviz.js/pull/198

### CODE REVIEW

**Comment by hasanbalci** [comment]
@metincansiper There seems to be no problem, can you please merge it?

**Comment by metincansiper** [comment]
@hasanbalci Thanks, I merged it.

@hasanbalci @ugurdogrusoz 
I realized that before this PR there was an inconsistency in default background color of submap. It was 0 for the submaps added later, but 0.5 for the ones that are loaded from the file. I used 0.5 for both cases since it is the default for any other node types. I can update it as 0 if needed.

**Comment by ugurdogrusoz** [comment]
@metincansiper if you mean transparency the default was no transparency for all simple nodes and something like 0.5 (check public Newt to make sure) for all compound nodes.

**Comment by ugurdogrusoz** [comment]
In case Newt isn't using default values in the libraries as defaults in the app, then it should do so.

**Comment by metincansiper** [comment]
>@metincansiper if you mean transparency the default was no transparency for all simple nodes and something like 0.5 (check public Newt to make sure) for all compound nodes.

@ugurdogrusoz What I mean was the background opacity. I think we mean the same thing. I checked the public Newt. It is 0.5 for all kind of nodes (both simple and compound) there (By the code I supposed that it would be 0 for compartment and submap but I was wrong it is consitently 0.5. I am not sure maybe the code is updated later). Looks like my changes did not make any difference on that. Therefore, I think we can ignore my question now.

If you want to I can change the default opacity of simple nodes to 0 as you mentioned but I think in that case we will not be able to see their background color.

**Comment by hasanbalci** [comment]
@metincansiper I think background opacities for simple nodes are set to 1 [here](https://github.com/iVis-at-Bilkent/newt/blob/c83bc8849dc9c42f1c618ef14cca77b93b9c11c1/app/js/app-cy.js#L630) in Newt sometime. I think @ugurdogrusoz wants this setting to be done in the default values. So I think it would be good to set the default opacity of simple nodes to 1 and remove the code in Newt. Thanks!

**Comment by ugurdogrusoz** [comment]
We would also like to have compound nodes to have some transparency (0.5)

**Comment by metincansiper** [comment]
@hasanbalci @ugurdogrusoz 
I can do the same thing that the line @hasanbalci mentioned by the library defaults. However, should we only handle simple node types or the simple nodes. For example, I think that complex is a compound node type but there would be a simple complex as well.

How about something like that all node types will have the default transparency of 1. However, if a node is compound the half of this value will be used upon rendering?

**Comment by ugurdogrusoz** [comment]
Let's simply default opacity to 1.0 for all simple node types and 0.5 for all compound node types (regardless of whether they are empty or not) at the library level. Newt should use the library defaults.

**Comment by metincansiper** [comment]
@ugurdogrusoz @hasanbalci 
I updated the defaults as desired. If I add new nodes to an empty map then defaults are used as expected. However, if I load some maps and add node then the opacity is set to 1 even for compound node types. This is only happening for some of the maps including "neuronal_muscle_signaling".

Also I see that in Newt there are some code segments (https://github.com/iVis-at-Bilkent/newt/blob/unstable/app/js/app-menu.js#L454, https://github.com/iVis-at-Bilkent/newt/blob/unstable/app/js/app-utilities.js#L1975, https://github.com/iVis-at-Bilkent/newt/blob/unstable/app/js/app-utilities.js#L1985, https://github.com/iVis-at-Bilkent/newt/blob/unstable/app/js/app-utilities.js#L2002) that set opacity to 1. I do not know the reason behind it and whether it will affect the desired functionality.

**Comment by ugurdogrusoz** [comment]
@metincansiper This is because the color scheme of the persisted file sets the opacity to 1.0. We talked with @dorukcakmakci . He is going to remove setting opacity during color scheme changes.

**Comment by ugurdogrusoz** [comment]
@dorukcakmakci is also going to set background-image-opacity to be the same as background-opacity during setting a background image.

**Pull request merged**
